### ISSUE TITLE
❌ Missing screenshot/preview/link to website

### ISSUE THREAD

**Issue by deannabosschert** [LarsBreuren/real-time-web-1920#1]
I'm missing a link to an actually served deployment or some other kind of preview of your website.
Would help a bit with understanding your concept better :)

![gif preview missing](https://media1.tenor.com/images/9218be0e29e5acb3e17d96a3f0b1e366/tenor.gif)

**Comment by LarsBreuren** [comment]
Very true, will add that in the future! Thanks
