### ISSUE TITLE
❌ Unnecessary font

### ISSUE THREAD

**Issue by deannabosschert** [LarsBreuren/real-time-web-1920#2]
# Unnecessary loading of font
I don't see you using this anywhere other than maybe using it for testing stuff so I'd recommend you take it out to save you on performance. Looks like an icon library and I'd recommend not using fonts for that anyways as it's less accessible.

https://github.com/LarsBreuren/real-time-web-1920/blob/71f833b01989ee4c92de3f34cd75b22743d4d9b9/views/partials/head.ejs#L7

![taking out the trash](https://media.giphy.com/media/3o6Mb8TVrTepl6sJtC/giphy.gif)

**Comment by LarsBreuren** [comment]
Shame! It will be deleted then.
